language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.0
script:
    - xcodebuild clean test -project Parrot.xcodeproj -scheme Parrot -destination "platform=iOS Simulator,name=iPhone X,OS=11.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
